services:
  - type: web
    name: pinterest-clone
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: pinterest-db
          property: connectionString

databases:
  - name: pinterest-db
    databaseName: pinterest
    user: pinterest_user